name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        channel:
          - dev
          - stable

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Removing example folder
        run: rm -rf example

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze
