display_name: FileFlow
packager: Tienisto
packagerEmail: dev.tien.donam@gmail.com
url: https://localsend.org
buildArch: x86_64
license: MIT

icon: assets/img/img_app_logo.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: An open source cross-platform alternative to AirDrop
summary: Share files easily with FileFlow
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
